const screens = {
	_testScreen: 'TestScreen',
	introduction: 'Introduction',
	home: 'Home',
	login: 'Login',
	loginSelect: 'LoginSelect',
	loginLoader: 'LoginLoader',
	loaderTeams: 'LoaderTeams',
	loaderEdit: 'LoaderEdit',
	readQr: 'ReadQr',
	writeQr: 'WriteQr',
	sell: 'Sell',
	orders: 'Orders',
	storage: 'Storage',
	listMergedStorage: 'ListMergedStorage',
	editOrder: 'EditOrder',
	editStorage: 'EditStorage',
	editProductsOrder: 'EditProductsOrder',
	loaderOrderInfo: 'LoaderOrderInfo',
	loaderCarryingOrders: 'CarryingLoader',
	loadersTeam: 'LoadersTeam',
	addLoader: 'AddLoader',
	addNonExistent: 'AddNonExistent',
	additionalCost: 'AdditionalCost',
}

export default screens
